Appsilon/shiny.semantic

R/semanticPage.R
R/shiny.R
R/uirender.R
man/getDeps.Rd
man/shiny_input.Rd
man/shiny_text_input.Rd
man/uirender.Rd
shiny.semantic.Rproj

I corrected the pkg documentation that was duplicating the description.

update decstiption and names

---

R/search_field.R

This solves hardcoded "Search..." string for search_field function.

default_text argument bug fix.

---

R/dsl.R

With that fix example from `dropdown` should work correctly.

list removed from menuitem

---

R/semanticPage.R

realted to Appsilon/semantic.dashboard#80

minor change to make dashboard responsive

---

README.md

https://app.asana.com/0/0/534016254067258/f

Add info about installation from CRAN

---

CHANGELOG.md

I tried to follow archive commits to fill it in, because it was actually empty.

CHANGELOG filled

---

inst/htmlwidgets/uirender.js
inst/htmlwidgets/uirender.yaml

UIrender wanted to take static files, so I inserted cdn address into element. Not the best solution (e.g. doesn't support themes), but good for now.

quick fix of uirender

---

DESCRIPTION

- Version 0.2.1 cause by fix of CDN_PATH
- changed maintainer from Filip to Dominik

version update and maintainer changed

---

R/semanticPage.R
man/semanticPage.Rd

Added support for static css path as requested in #86 .

Static css

---

README.Rmd

librabry should be library in Readme.Rmd

fix mis-spelling

---

README.Rmd
README.md
docs/index.html

domain change

---

R/semantic_search.R
man/dropdown.Rd
man/search_selection_choices.Rd

Add settings to dropdown.

---

R/modal.R
tests/testthat/test_modal.R

Allow passing argument to the modal as a list of arguments containing params for a parent tag.

Change in passing arguments to modal function.

---

docs/index.html

fix for https://appsilon.github.io/shiny.semantic/
removed merge conflicts and redundant  tags
closes #122

Fix conflicts

---

R/semanticPage.R

Remove duplicated trailing slash.

Remove trailing slash.

---

R/checkbox.R
man/SUPPORTED_THEMES.Rd
man/checkbox_positions.Rd
man/multiple_checkbox.Rd
man/semantic_palette.Rd

See: https://fomantic-ui.com/modules/checkbox.html#slider

Add type parameter for multiple radio.

---

DESCRIPTION

added contributors

---

.github/workflows/main.yml

test install vctrs

---

R/button.R
R/slider.R
man/actionbutton.Rd
man/uibutton.Rd
man/uislider.Rd

addresses problem mentioned in #176

unified notation class/type where necessary

---

inst/www/shiny-semantic-dropdown.js

Turn off rate policy for dropdown.

---

R/button.R
README.md
docs/CHANGELOG.html
docs/index.html
docs/pkgdown.yml
docs/reference/FOMANTIC_SIZE_LEVELS.html
docs/reference/actionButton.html
docs/reference/digits2words.html
docs/reference/extract_icon_name.html
docs/reference/horizontal_menu.html
docs/reference/icon.html
docs/reference/numericInput.html
docs/reference/rating.html
docs/reference/render_menu_link.html
docs/reference/selectInput.html
docs/reference/semantic_DT.html
docs/reference/updateActionButton.html
docs/reference/updateNumericInput.html
docs/reference/updateRating.html
docs/reference/updateSelectInput.html
man/actionButton.Rd
man/updateActionButton.Rd

Add examples to buttons' functions.
Covers first 2 elements from this issue:
https://github.com/Appsilon/shiny.semantic/issues/209

Buttons examples

---

R/checkbox.R
R/dsl.R
man/uidropdown.Rd
man/uiicon.Rd
man/uilabel.Rd
man/uimenu.Rd
man/uimessage.Rd
tests/testthat/test_dsl.R

[change] changed type to class in ui elements

---

R/input.R
docs/pkgdown.yml
docs/reference/numeric_input.html
docs/reference/textAreaInput.html
docs/reference/text_input.html
docs/reference/uiinput.html
docs/reference/update_numeric_input.html
man/numeric_input.Rd
man/textAreaInput.Rd
man/text_input.Rd
man/uiinput.Rd
man/update_numeric_input.Rd

Add examples to input functions

---

R/rating.R
inst/www/shiny-semantic-rating.js

Because rating code was a little bit overcomplicated, based on my example from tech talk I just wanted to fix this.
Closes #251 
**DoD**

Simplify rating binding.

---

inst/www/shiny-semantic-slider.js

Fix slider checkbox style.

---

R/semanticPage.R
docs/articles/intro.html
docs/articles/semantic_integration.html
docs/index.html
docs/pkgdown.yml
docs/reference/action_button.html
docs/reference/calendar.html
docs/reference/card.html
docs/reference/cards.html
docs/reference/date_input.html
docs/reference/dropdown_input.html
docs/reference/grid.html
docs/reference/icon.html
docs/reference/label_tag.html
docs/reference/modal.html
docs/reference/multiple_checkbox.html
docs/reference/progress.html
docs/reference/search_field.html
docs/reference/search_selection_choices.html
docs/reference/semanticPage.html
docs/reference/shiny_input.html
docs/reference/shiny_text_input.html
docs/reference/slider.html
docs/reference/tabset.html
docs/reference/uirender.html
docs/reference/update_action_button.html
docs/reference/update_dropdown_input.html
man/semanticPage.Rd

Fix typo in suppress bootstrao param.

---

_pkgdown.yml
docs/articles/intro.html
docs/articles/semantic_integration.html
docs/pkgdown.yml
docs/reference/index.html

Add grid and layouts to ref

---

examples/app.R

Added `toast` example + minor fixes to main example app.
Fixes #297

added toast example to main example app

---

R/grid.R
man/grid.Rd
man/grid_template.Rd
man/list_of_area_tags.Rd
tests/testthat/test_grid.R
tests/testthat/test_layouts.R

Short description (with a reference to an issue):
**1) I implemented support for grid responsiveness (on mobile)**
See blogpost draft for some examples: https://docs.google.com/document/d/1AvO1L-e5QH-K0KtcvE3pnjuwCCQxjouYEdnC1OFdC_w/edit#
**2) Grid now supports selector ID for grid container div and grid areas divs**
**DoD**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/appsilon/shiny.semantic/316)

Mobile grid

---

examples/app.R
examples/grid/app.R

Grid example

---

DESCRIPTION
R/calendar.R
examples/app.R
examples/calendar/app.R
tests/testthat/test_calendar.R

Fix calendar timezone bug

---

examples/dropdown_updates/app.R
inst/www/shiny-semantic-dropdown.js

closes #327 
I had a go at this and I was able to make the dropdown closes every time the user selects an option.
**DoD**

[WIP] Dropdown Bug

---

R/dropdown.R

[change] update select input has default label set to null

---

inst/www/shiny-semantic-slider.js

Fixing standard sliders

---

R/layouts.R

Fix sidebar_layout rendering by assigning variables to all parameters in grid function

---

DESCRIPTION

Fixes CI builds.
Adds `markdown` ot Suggests which is now required for building vignettes using the `knitr::knitr` engine (https://github.com/yihui/knitr/issues/1864). 
**DoD**

Add markdown to DESCRIPTION to fix CI

---

vignettes/basics.Rmd

Fixed invalid URL's in vignette.
**DoD**

Fix invalid URL in vignette

---

.github/workflows/main.yml

Add R-devel and R-oldrel to CI

---

DESCRIPTION
R/dropdown.R
man/shiny.semantic.Rd
man/update_dropdown_input.Rd

Issue #455 
Old function was used in an example. The example could not be used. 
**DoD**

fix: updated function that was used in an example

---

NEWS.md

*Have you read the [Contributing Guidelines](https://github.com/Appsilon/.github/blob/main/CONTRIBUTING.md)?*
Issue #
*Clear and concise description of what changed and why.
If necessary, include screenshots and/or a step-by-step guide on how to test the changes.*

chore: Change version in NEWS.
