Appsilon/shiny.semantic

- inst/www/dist.js
- inst/www/shiny-binding.js
This change allows shiny apps to call update*Input methods to update the value of an input.
It mostly based on the code from https://github.com/rstudio/shiny/blob/9613c58bf8120bcfdab35801b17167418b5464ac/srcjs/input_binding_text.js#L26
> Enable updateTextInput for shiny inputs.

- R/dsl.R
This PR changes uiicon so that you can pass any attributes (fot example `class`), not only `style`
> Generalize uiicon.

- DESCRIPTION
- LICENSE
- LICENSE.md
- inst/prepare_package_cran.sh
Created new LICENSE.md file with full MIT license text. LICENSE file shortened as MIT template requires.
Fixed other simple notes such as mis-spelled words and form of urls in Description section.
> Cran release fixes

- R/modal.R
- examples/modal/app_5.R
- man/modal.Rd
Closes #125
Updated documentation to better explain the difference between using `...` and content. In general:
- `...` can be used as a quick way to add elements to the modal content. This is the most common use.
- `content` allows developers to fully customize the attributes of the content container. This includes HTML attributes such as data or classes for example. This rule is also true for the `header` and `footer` arguments.
> Update modal documentation

- R/semanticPage.R
- inst/htmlwidgets/uirender.js
resolve https://github.com/Appsilon/datavalidator/issues/11
resolve #94 
This PR adding load dependencies to the head.
Small fix for `minified` option.
> Fix loading semantic js for rmarkdown component.

- R/checkbox.R
In standard shiny, `selected` is chosen on value level not value names.
The change does exactly the same for checkboxes in shiny.semantic.
> Use choices values not names for selected checkbox.

- R/semanticPage.R
- man/semanticPage.Rd
Without margin all our examples look like this:
margin highlights the shading and other elements.
> added margin to semanticpage

- R/dropdown.R
- examples/dropdown_updates/app.R
- inst/www/shiny-semantic-dropdown.js
Fixes #308 .
Contributes to #313 
A bit hacky, but this should help.
**DoD**
> fixed dropdown when multiple inputs are needed

- R/input.R
The second argument of `shiny::testInput` is `label`. This caused that `value` was passed as `label`.
> Fix passing `value` as `label` in `textInput`

- DESCRIPTION
- R/semanticPage.R
Inline styles are bad. Setting min-height of `<body>` to a magic number is bad.
This small PR removes two bad things contained in just a few characters.
This `min-height` was causing real responsiveness problems in `semantic.dashboard` that had to be overwritten using `!important` which is bad but is (soon hopefully _was_ necessary).
**DoD**
> Remove inline-styled min-height from <body>

- inst/www/shiny-semantic-tabset.js
Related to this [issue](https://github.com/Appsilon/shiny.semantic/issues/347)
When using a `tabset` and setting a class different of `.tabular.menu` as @ashbaldry suggested, the `find` method was unable to find the newly set class and hence unable to run the others method as expected. 
Setting the scope of the find function as `ui.menu.sem` once again as @ashbaldry suggested, fix the issue. 
**DoD**
> Fixing - Tabset won't work after changing its class trough the menu_class arg

- R/progress.R
- examples/progress/app.R
- inst/www/shiny-semantic-progress.js
Unbinding the progress bar as an input, but still accessible through `input$id`. Updates like the `Progress` toast and can be updated server side as before.
Tested against #359 and the 4 updates in the examples and all seem to work okay.
**DoD**
> Enabling Progress Bar to Update in Loops. Fixes #359

- DESCRIPTION
Fixes the build to work with the latest version of knitr:
```
── R CMD build ─────────────────────────────────────────────────────────────────
* checking for file ‘.../DESCRIPTION’ ... OK
* preparing ‘shiny.semantic’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
Error: --- re-building ‘fomantic_js.Rmd’ using rmarkdown
Error: Error: processing vignette 'fomantic_js.Rmd' failed with diagnostics:
The 'rmarkdown' package should be installed and declared as a dependency of the 'shiny.semantic' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'rmarkdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
--- failed …
```
> Fix the build for latest knitr

- R/input.R
Closes #370 
The `value` parameter for `textAreaInput()` is currently passed to `text_input()` as the label (#370). This PR fixes that issue.
**DoD**
> Fixed `textAreaInput` value parameter

- R/modal.R
- examples/modal/app_6.R
- man/modal.Rd
Issue: https://github.com/Appsilon/shiny.semantic/issues/377
I think we have some mess in the functions to remove modals - removeModal() actually hides all modals, the same as remove_all_modals, while remove_modal tries to use shiny::removeUI. I will ask on Slack if and how we want to clean this up.
For now I just updated the example to hide the modal and it should work fine.
**DoD**
> Ania.update modal example

- .Rbuildignore
- DESCRIPTION
- R/utils.R
- tests/testthat/test_utils.R
- vignettes/basics.Rmd
This PR adopts `warn_unsupported_args` to a R-devel implementation of `base::intersect`
R-devel implementation of `intersect` returns `NULL` if one of arguments is `NULL`. Previous implementations of `intersect` return a vector of length 0, of type same as the non-NULL argument, i.e. `intersect("A", NULL)` yields `NULL` in R-devel in contrast to prevoiusly returned `character(0)` 
Additionally this PR resolves some of CRAN check notes regarding vignettes and invalid URL's, e.g.
> Found the following (possibly) invalid file URI:
URI: fomantic-ui.com/
From: inst/doc/basics.html
Closes #393 
**DoD**
> CRAN R-devel fix

- R/checkbox.R
- tests/testthat/test_checkbox.R
Prior to this change `checkboxInput()` would throw an error with a default width value. This change makes the warning go off only if width argument is not `NULL`.
Fixes #404 
**DoD**
> fix: remove unnecessary warning

- .github/workflows/main.yml
- DESCRIPTION
> Fix failing ci

- R/input.R
- man/numeric_input.Rd
- tests/testthat/test_input.R
This PR closes the following issue: #428 
It includes a change in the tag creation of the `numeric_input`
Additionally, the checks that the placeholder type is character.
It also has the updated unit tests to check as well the placeholder argument.
This app creates a placeholder as `value` in the `numeric_input` is NULL
```
library(shiny)
library(shiny.semantic)
ui <- semanticPage(
numeric_input("ex", "Select number", value = NULL, placeholder = "type value")
)
server <- function(input, output, session) {}
shinyApp(ui, server)
```
**DoD**
> Add placeholder to numeric_input

- .github/pull_request_template.md
- .github/workflows/main.yml
This PR:
- fixes formatting of the PR template
- reduced eagerness of CI (it won't run on every single push to every single branch anymore)
The latter came when I saw workflow trigger on markdown change 😬
> Format PR template and limit workflow runs

- DESCRIPTION
- NEWS.md
- R/dropdown.R
- inst/www/shiny-semantic-dropdown.js
- man/update_dropdown_input.Rd
- tests/testthat/test_dropdown.R
Prior to this change only multi-selection dropdown could be cleared. This change makes `update_dropdown_input` behavior analogous to `shiny::updateSelectInput`.
Note: this is a breaking change. Prior to this commit updating with `character(0)` or `""` did not have any effect.
Closes #458 
**DoD**
- ~~All interaction with a semantic functions, examples and docs are written from the perspective of the person using or receiving it. They are understandable and helpful to this person.~~
- ~~All code has been peer-reviewed before merging into any main branch.~~
- ~~All changes have been merged into the main branch we use for development (develop).~~
- ~~Any added or touched code follows our style-guide.~~ The entire codebase could be run through a formatter, so I didn't update this single file.
> 458 dropdown clear
